# Generated by Django 3.2.15 on 2022-09-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='summary',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
