# Generated by Django 3.2.15 on 2022-09-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_alter_userprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('young_coder', 'Young Coder'), ('college_student', 'College Student'), ('career_change', 'Career Change')], default='career_change', max_length=50),
        ),
    ]
