# Generated by Django 3.2.15 on 2022-09-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
    ]
